version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "3001:3001"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434

  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3001
